version: '3.7'

volumes:
    database:

services:
    stock-ml-db:
        image: mariadb:10.5.6
        build: database/.
        restart: unless-stopped
        volumes:
            - "database:/var/lib/mysql"
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: server
        networks:
        - stock-ml-network-extern
        - stock-ml-network-intern
        
    stock-ml-web:
        build: stockml/.
        command: python3 manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        networks:
        - stock-ml-network-extern
        - stock-ml-network-intern

networks:
    stock-ml-network-extern:
        driver: bridge
    stock-ml-network-intern:
