apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    run: web
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
  type: LoadBalancer
  loadBalancerIP: 20.50.39.128