name: Django CI Image

on:
  push:
    branches: [ main ]

jobs:
  multi:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]
        
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - 
        name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - 
        name: Run Tests
        run: |
          cd stock-ml-web/
          python manage.py test
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/stock-ml-web:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - 
        uses: azure/k8s-set-context@v1
        with:
          kubeconfig: '${{ secrets.AZURE_CREDENTIALS }}'

      - 
        uses: azure/k8s-deploy@v1
        with:
          manifests: |
            kubernetes/web-deployment.yaml
            kubernetes/web-service.yaml

